<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <AssemblyName>MMHOOK_Assembly-CSharp</AssemblyName>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
        <Reference Include="Assembly-CSharp">
            <HintPath>../../HKMP/lib/Assembly-CSharp.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
