// PlayMaker FSM Action stubs
namespace HutongGames.PlayMaker.Actions {
    public class ActivateAllChildren : FsmStateAction { }
    public class ActivateGameObject : FsmStateAction { }
    public class AddComponent : FsmStateAction { }
    public class ApplyMusicCue : FsmStateAction { }
    public class AudioPlay : FsmStateAction { }
    public class AudioPlayInState : FsmStateAction { }
    public class AudioPlayRandom : FsmStateAction { }
    public class AudioPlaySimple : FsmStateAction { }
    public class AudioPlayerOneShot : FsmStateAction { }
    public class AudioPlayerOneShotSingle : FsmStateAction { }
    public class AudioStop : FsmStateAction { }
    public class CallMethodProper : FsmStateAction { }
    public class CreateObject : FsmStateAction { }
    public class DestroyComponent : FsmStateAction { }
    public class DestroyObject : FsmStateAction { }
    public class FindAlertRange : FsmStateAction { }
    public class FindChild : FsmStateAction { }
    public class FindGameObject : FsmStateAction { }
    public class FireAtTarget : FsmStateAction { }
    public class FlingObjectsFromGlobalPool : FsmStateAction { }
    public class FlingObjectsFromGlobalPoolTime : FsmStateAction { }
    public class FlingObjectsFromGlobalPoolVel : FsmStateAction { }
    public class GetChild : FsmStateAction { }
    public class GetHero : FsmStateAction { }
    public class GetOwner : FsmStateAction { }
    public class GetParent : FsmStateAction { }
    public class GetPosition : FsmStateAction { }
    public class GetRandomChild : FsmStateAction { }
    public class MoveLiftChain : FsmStateAction { }
    public class PlayParticleEmitter : FsmStateAction { }
    public class SceneAdditiveLoadConditional : FsmStateAction { }
    public class SendEventByName : FsmStateAction { }
    public class SendEventByNameV2 : FsmStateAction { }
    public class SendHealthManagerDeathEvent : FsmStateAction { }
    public class SendMessage : FsmStateAction { }
    public class SendRandomEventV2 : FsmStateAction { }
    public class SendRandomEventV3 : FsmStateAction { }
    public class SetActiveGameObject : FsmStateAction { }
    public class SetAnimationTime : FsmStateAction { }
    public class SetAudioClip : FsmStateAction { }
    public class SetAudioPitch : FsmStateAction { }
    public class SetAudioVolume : FsmStateAction { }
    public class SetBoolValue : FsmStateAction { }
    public class SetCollider : FsmStateAction { }
    public class SetColorValue : FsmStateAction { }
    public class SetDamageHeroAmount : FsmStateAction { }
    public class SetFloatValue : FsmStateAction { }
    public class SetGameObject : FsmStateAction { }
    public class SetIntValue : FsmStateAction { }
    public class SetMaterialColor : FsmStateAction { }
    public class SetMeshRenderer : FsmStateAction { }
    public class SetParent : FsmStateAction { }
    public class SetPlayerDataBool : FsmStateAction { }
    public class GetPlayerDataBool : FsmStateAction { }
    public class SetPlayerDataInt : FsmStateAction { }
    public class GetPlayerDataInt : FsmStateAction { }
    public class SetPlayerDataFloat : FsmStateAction { }
    public class GetPlayerDataFloat : FsmStateAction { }
    public class SetPlayerDataString : FsmStateAction { }
    public class GetPlayerDataString : FsmStateAction { }
    public class SetPosition : FsmStateAction { }
    public class SetRotation : FsmStateAction { }
    public class SetScale : FsmStateAction { }
    public class SetSpriteMaterial : FsmStateAction { }
    public class SetTextMeshProText : FsmStateAction { }
    public class SetVelocity2d : FsmStateAction { }
    public class Tk2dPlayAnimation : FsmStateAction { }
    public class Tk2dPlayAnimationWithEvents : FsmStateAction { }
    public class Tk2dSetSprite : FsmStateAction { }
    public class Tk2dWatchAnimationEvents : FsmStateAction { }
    public class TransitionToAudioSnapshot : FsmStateAction { }
    public class Wait : FsmStateAction { }
    public class WaitRandom : FsmStateAction { }
}
